### ISSUE TITLE
Error when logging in with newly created Trakt API App: name 'time' is not defined

### ISSUE THREAD

**Issue by CypherNL** [po5/player-tracker#1]
```
Please visit the following link in your browser https://trakt.tv/oauth/applications/new
- Give your app a name
- Set the redirect URI to 'urn:ietf:wg:oauth:2.0:oob'
- Enable the '/scrobble' permission
- Press 'Save App'
Enter your Trakt.tv client id: ***
Enter your Trakt.tv client secret: ***
Traceback (most recent call last):
  File "player-tracker.py", line 11, in <module>
    import services
  File "E:\Downloads\player-tracker-master\player-tracker-master\services\__init__.py", line 4, in <module>
    from . import trakt
  File "E:\Downloads\player-tracker-master\player-tracker-master\services\trakt.py", line 113, in <module>
    tokens = token(client_id, client_secret)
  File "E:\Downloads\player-tracker-master\player-tracker-master\services\trakt.py", line 70, in token
    start = time.time()
NameError: name 'time' is not defined
PS E:\Downloads\player-tracker-master\player-tracker-master>
```

**Comment by CypherNL** [comment]
I can now login into Trakt with this program. Thanks! 👍
