### ISSUE TITLE
Anilist updates episodes that is out of range (2223 out of 12), while MAL does not

### ISSUE THREAD

**Issue by CypherNL** [po5/player-tracker#2]
**OS:** Windows 10 1607 LTSB
**player-tracker version:** 1fa74e65a326370729f55a67f2e09f8aea9768e7

I've got the SCP-2223 release of Kaiba and the AniList and MyAnimeList parses the episode counts differently.

If i play episode 1, AniList parses the SCP-2223 section as the episode count and updates that to AniList.
The MyAnimeList updater however parses the actual episode count, episode 1. On the first try it updated to MyAnimeList successfully while the second try outputs a Traceback error.

The second episode also updated successfully on the first try while AniList stays at episode 2223.

```
PS E:\Downloads\player-tracker-master\player-tracker-master> python.exe .\player-tracker.py
Updating AniList...
Updating MyAnimeList...
Waiting 30s...
Searching on anilist...
Our best match is カイバ - Season 1 Episode 2223
Searching on myanimelist...
Our best match is Kaiba - Season 1 Episode 1
Traceback (most recent call last):
  File ".\player-tracker.py", line 133, in <module>
    search_and_match(**info)
  File ".\player-tracker.py", line 121, in search_and_match
    update(module, match, format)
  File ".\player-tracker.py", line 127, in update
    module.update(match["id"], match["season"], match["episode"], match["completed"], format)
  File "E:\Downloads\player-tracker-master\player-tracker-master\services\myanimelist.py", line 51, in update
    episodes = int(document.css("#anime_num_episodes")[0].attributes["value"])
IndexError: list index out of range
PS E:\Downloads\player-tracker-master\player-tracker-master>
```

**Comment by CypherNL** [comment]
Can confirm it's fixed! 👍 
```
PS E:\Downloads\player-tracker-master\player-tracker-master> python.exe .\player-tracker.py
Updating AniList...
Updating MyAnimeList...
Updating Trakt.tv...
Waiting 30s...
Searching on anilist...
Our best match is Kaiba - Season 1 Episode 1
Searching on myanimelist...
Our best match is Kaiba - Season 1 Episode 1
Searching on trakt...
Our best match is Kaiba - Season 1 Episode 1
Waiting 30s...
```
